### ISSUE TITLE
Node load balancer service healthport checker

### ISSUE THREAD

**Issue by bjqian** [Azure/kdebug#25]
## background 
There is a [healthping](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-custom-probe-overview) [tcp/http] from Azure Load balancer to k8s node.
The loadbalancer users this ping to detect the active VMs for k8s service.

## Implemention 
Fetch all the services with type loadbalancer. 
Find the corresponding pods selected by the service.
Try establish a tcp connection/send a http request to the healthcheckport of the pod's node.

## Benefits and limitations
This is useful to debug the loadbalncer drainer. 
But other tool users may not need this checker.

**Comment by ArchangelSDY** [comment]
Closing this as it seems no longer valid.
