### ISSUE TITLE
Pod network connectivity

### ISSUE THREAD

**Issue by ArchangelSDY** [Azure/kdebug#45]
Ideas:

* A tool mode to assess specific pod network conditions?

**Comment by zackliu** [comment]
A tool mode command to auto or manual check network connectivity in some container's pod. 
basic usage: `kdebug -t connectivity -p <pid>` It will auto check the connectivity with some endpoints.
Alternative parameters
 - `--connectivity.pod`  pod-name
 - `--connectivity.container` container-id
 - `--connectivity.manual` pass the command to the container network namespace and return the result.
