### ISSUE TITLE
Tool mode: Inspect package upgrades

### ISSUE THREAD

**Issue by ArchangelSDY** [Azure/kdebug#48]
# Background

It's proved to be not rare that a package upgrade could break functionalities, especially when it's triggered by an auto upgrade. Digging into apt/dpkg/unattended-upgrade logs are not trivial. Let's provide a simple way.

# Goals

* Provide a simple view of upgrades packages. Columns: timestamp, package name, old version, new version. Discard other info.
* Point out raw logs file locations for users to do further inspection.

**Comment by qinzhouxu** [comment]
Hi @ArchangelSDY, I'm working on this issue.
