### ISSUE TITLE
Switch OOM checker kernel log source

### ISSUE THREAD

**Issue by ArchangelSDY** [Azure/kdebug#70]
# Background
Currently OOM checker reads kernel logs from `/var/log/kern.log`. However this file is not guaranteed to exist on all systems. Instead, we'd better read from `/dev/kmsg` directly.

# References
* https://www.kernel.org/doc/Documentation/ABI/testing/dev-kmsg

**Comment by bjqian** [comment]
Looks the log pattern is completely same. 
But reading /dev/kmsg needs **Root** permission

**Comment by ArchangelSDY** [comment]
We can check what we have at the beginning (permission / file existence/ ...) and choose the best way.
